sudo: required
services:
  - docker
before_install:
  - docker pull yjkim0/php-travis
  - docker run -d -v `pwd`:/var/www --name php-travis yjkim0/php-travis
  - docker ps -a
before_script:
  - docker exec php-travis /bin/sh -c "cd /var/www; composer update"
  - docker exec php-travis /bin/sh -c "cd /var/www; ./vendor/bin/phpcs -sw --standard=PSR2 --ignore=config.php app"
  - docker exec php-travis /bin/sh -c "cd /var/www; ./vendor/bin/phpmd app text cleancode"
script:
  - docker exec php-travis /bin/sh -c "cd /var/www; phpunit"
